[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

[dev]
  command = "npm run start"
  port = 3006
  targetPort = 3006
  publish = "build"
  autoLaunch = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
